### ISSUE TITLE
Enhancement request: Usage of Cobra CLI 

### ISSUE THREAD

**Issue by MrAzharuddin** [intelops/genval#24]
Hi @santoshkal @devopstoday11 ,

can we use cobra to make our cli user friendly and for good code practices and maintainable. Looking for your response.

Thanks

**Comment by santoshkal** [comment]
Hi @MrAzharuddin

Thanks for raising the idea of integrating Cobra for a more user-friendly and maintainable CLI.

I am actively working on an upcoming update that will include Cobra integration with features requested in issues #15, #16, and #25.
